### ISSUE TITLE
[BUG] Game crash on Naga kill in Twilight Forest

### ISSUE THREAD

**Issue by vianilambo** [nickmachiavelli7/Frenpack-XServer#8]
**Describe the bug**
After killing the Naga, in the Twilight Forest, my client crashed and the server registered an error.

Server Error:

18.06 13:29:55 [Server] Netty IO #2/ERROR [FML]: NetworkDispatcher exception
18.06 13:29:55 [Server] INFO java.io.IOException: Connection reset by peer
18.06 13:29:55 [Server] INFO at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_292]
18.06 13:29:55 [Server] INFO at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_292]
18.06 13:29:55 [Server] INFO at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_292]
18.06 13:29:55 [Server] INFO at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_292]
18.06 13:29:55 [Server] INFO at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[?:1.8.0_292]
18.06 13:29:55 [Server] INFO at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
18.06 13:29:55 [Server] INFO at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
18.06 13:29:55 [Server] INFO at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
18.06 13:29:55 [Server] INFO at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
18.06 13:29:55 [Server] INFO at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
18.06 13:29:55 [Server] INFO at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
18.06 13:29:55 [Server] INFO at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
18.06 13:29:55 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
18.06 13:29:55 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
18.06 13:29:55 [Disconnect] User MaxMade has disconnected, reason: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Connection reset by peer], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

**Date & Time**
06/18 13:29 Server Time

**To Reproduce**
Kill a naga? in twilight forest

**Log Files**
Please zip the "crash-reports" and "logs" folders from your local client and place them here if the issue is a client crash or lag issue.
[crash-2021-06-18_15.29.53-client.txt](https://github.com/nickmachiavelli7/Frenpack-XServer/files/6679234/crash-2021-06-18_15.29.53-client.txt)

**Additional context**

**Comment by vianilambo** [comment]
https://github.com/TeamTwilight/twilightforest/issues/583
